const tabela2024 = [

    {
        nome: 'São Paulo',
        sigla: 'SP',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Atletico-GO',
        sigla: 'AG',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Athletico PR',
        sigla: 'CP',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Fluminence',
        sigla: 'FU',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Botafogo',
        sigla: 'BF',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Internacional',
        sigla: 'IT',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Grêmio',
        sigla: 'GR',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Santos',
        sigla: 'ST',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Flamengo',
        sigla: 'FA',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Corinthians',
        sigla: 'CR',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Palmeiras',
        sigla: 'PA',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    }

];

export default tabela2024;